### ISSUE TITLE
Integration with ACF 

### ISSUE THREAD

**Issue by bibi-babi** [tommcfarlin/page-template-example#15]
Hello,
I'm using your code to implement a template via plugins.
To change the template from the admin side using ACF advanced custom fields. [www.advancedcustomfields.com](http://www.advancedcustomfields.com)

So everything is right, but I found a problem:

When I open the Site template list using the plugin ACF, the law there are no templates loaded with your code.

I do not understand why. They should not be recorded in the wordpress system?
Can you find a solution?

Thanks for your code and your support
bye

**Comment by tommcfarlin** [comment]
This particular plugin is used just for example purposes and it's really meant to be used as a 'production-level' plugin, so I won't be adding support for this plugin to work with others.
